<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<a class="btn btn-default" role="button" href='/login/view'>登录</a>
<a class="btn btn-default" role="button" href='/register/view'>注册</a>
<a class="btn btn-default" role="button" href='/todo/all'>todo</a>
<a class="btn btn-default" role="button" href='/'>HOME PAGE 主页</a>
<a class="btn btn-default" role="button" href='/message'>message</a>
<img src='/doge.gif'>
<img src='/doge2.gif'>
<img src='/doge1.jpg'>


<h1>${message}</h1>

</body>
</html>